server:
  adminPort: 8080
  logLevel: info

hap:
  bridgeName: "Home Hub"
  pin: "743-29-816"
  setupId: "HUB1"
  port: 51826
  storagePath: ./.data/hap

database:
  path: ./.data/hub.db

adapters:
  - id: dummy-ac
    configFile: ./config/adapters/dummy-ac.yaml
