// 447 MHz RF bridge — ESP32 + CC1101, two remotes, one radio.
//
//   ESP32 (WiFi) --MQTT--> Home Assistant on a Raspberry Pi
//   ESP32 (SPI)  --------> CC1101 --OOK--> ceiling fan / blind receivers
//
// The two remotes need genuinely different handling, not just different bytes:
//
//   Remote 01, ceiling fan   447.887 MHz   33-bit   GENERATED
//     Its frame carries a 3-bit press counter plus four check bits derived from
//     the button and that counter. The receiver uses the counter to tell one
//     press from the 7-13 repeats inside it, so replaying a captured frame
//     would repeat a value it has already consumed. Frames must be built.
//
//   Remote 02, 16-ch blind   447.7234 MHz  97-bit   REPLAYED
//     Its payload is encrypted with no recoverable field structure, but the code
//     set is small and fully captured, so replay works without breaking the
//     cipher. There is no counter — the same frame works every time.
//
// Both live in protocols.h, generated by tools/gen_codebook_header.py from the
// analyzer's verified captures. Regenerate rather than editing it.
//
// VERIFIED ON HARDWARE (2026-08-10, ESP32 + CC1101 clone, Airspy as witness)
//   CC1101 VERSION=0x14, SPI and OOK config work as written.
//   Blind: transmitted ch01/down hold -> decoded step x19 + full x12, bit-exact
//          against the codebook; pulse widths +5/+6 us; carrier 447.72355 MHz.
//   Fan:   transmitted buttons 1 and 5 -> both frames bit-exact against the
//          generator including address, button code, counter and parity;
//          carrier 447.88701 MHz.
// Re-check any time with:
//   python3 -m rfremote verify --files <capture>     (blind)
//   python3 -m rfremote analyze <capture> --freq 447.887   (fan)
//
// What is still unconfirmed: whether the actual fan and blind receivers act on
// these transmissions, and whether the blind's STOP really is the enter button.
// Neither can be settled without the devices present.
//
// WIRING — the module is 1.8-3.6 V. VCC on 5V destroys it.
//
//   CC1101            ESP32
//   1 GND             GND
//   2 VCC             3V3          <-- never 5V
//   3 GDO0            GPIO 25      TX data out (ESP32 drives this)
//   4 CSN             GPIO 5
//   5 SCK             GPIO 18
//   6 MOSI            GPIO 23
//   7 MISO/GDO1       GPIO 19
//   8 GDO2            GPIO 26      RX data in (interrupt)

#include <Arduino.h>
#include <SPI.h>
#include <WiFi.h>
#include <Preferences.h>
#include <PubSubClient.h>

#include "protocols.h"

// ---------------------------------------------------------------- user config

// WiFi and broker credentials live in secrets.h, which is NOT committed.
// Copy secrets.h.example to secrets.h and fill it in; the hub's embedded
// broker is the MQTT_HOST (see configs/devices.yaml mqtt.listen).
//
// An empty SSID is the "not configured" test rather than a sentinel string,
// because a sentinel would appear twice — here and in the check — and a
// find-and-replace of the credentials would silently disable the check too.
#include "secrets.h"

static const char *DEVICE_ID = "rf447";
static const char *DEVICE_NAME = "447MHz RF Bridge";

// Blind channels to expose. Must exist in protocols.h.
static const uint8_t kBlindChannels[] = {0, 1, 2, 3};
static const size_t kBlindChannelCount =
    sizeof(kBlindChannels) / sizeof(kBlindChannels[0]);

// Output power. The Korean 447.6-447.85 MHz allocation is 5 mW (7 dBm) or less;
// 0x84 is about +5 dBm, 0xC8 (+7 dBm) is the ceiling, 0xC0 (+10 dBm) is over it.
// Note the fan's own 447.887 MHz sits just *above* that allocation.
static const uint8_t PA_POWER = 0x84;

// ------------------------------------------------------------------ CC1101 io

static const int PIN_CSN = 5, PIN_SCK = 18, PIN_MISO = 19, PIN_MOSI = 23;
static const int PIN_GDO0 = 25;      // async TX data in to CC1101
static const int PIN_GDO2 = 26;      // async RX data out of CC1101

enum {
  REG_IOCFG2 = 0x00, REG_IOCFG0 = 0x02, REG_FIFOTHR = 0x03,
  REG_PKTCTRL0 = 0x08, REG_CHANNR = 0x0A,
  REG_FSCTRL1 = 0x0B, REG_FSCTRL0 = 0x0C,
  REG_FREQ2 = 0x0D, REG_FREQ1 = 0x0E, REG_FREQ0 = 0x0F,
  REG_MDMCFG4 = 0x10, REG_MDMCFG3 = 0x11, REG_MDMCFG2 = 0x12,
  REG_MDMCFG1 = 0x13, REG_MDMCFG0 = 0x14, REG_DEVIATN = 0x15,
  REG_MCSM1 = 0x17, REG_MCSM0 = 0x18, REG_FOCCFG = 0x19, REG_BSCFG = 0x1A,
  REG_AGCCTRL2 = 0x1B, REG_AGCCTRL1 = 0x1C, REG_AGCCTRL0 = 0x1D,
  REG_FREND1 = 0x21, REG_FREND0 = 0x22,
  REG_FSCAL3 = 0x23, REG_FSCAL2 = 0x24, REG_FSCAL1 = 0x25, REG_FSCAL0 = 0x26,
  REG_TEST2 = 0x2C, REG_TEST1 = 0x2D, REG_TEST0 = 0x2E,
  REG_PARTNUM = 0x30, REG_VERSION = 0x31, REG_RSSI = 0x34, REG_MARCSTATE = 0x35,
  REG_PATABLE = 0x3E,
};
enum { CMD_SRES = 0x30, CMD_SCAL = 0x33, CMD_SRX = 0x34, CMD_STX = 0x35,
       CMD_SIDLE = 0x36 };

// FREQ2/1/0 = round(f * 2^16 / f_xtal).
//
// f_xtal is NOT the 26 MHz printed on the module. Measured against the SDR, this
// board transmitted 40.1 kHz low — a -89.6 ppm crystal error, which is ordinary
// for a cheap clone but far too much to ignore: the target sits on a 12.5 kHz
// channel grid, so 40 kHz off is three channels away. These values are
// calibrated for THIS module at 25,997,670 Hz.
//
// To recalibrate another module: flash, transmit, measure with
//   python3 -m rfremote listen --freq 447.725 --gain 6
// then f_xtal = 26e6 * measured / commanded, and recompute both triples.
#define XTAL_HZ 25997670.0
struct Carrier { uint8_t f2, f1, f0; const char *name; };
static const Carrier kFanCarrier   = {0x11, 0x3A, 0x5C, "447.887 MHz (fan)"};
static const Carrier kBlindCarrier = {0x11, 0x38, 0xC0, "447.723 MHz (blind)"};

static SPISettings kSpi(4000000, MSBFIRST, SPI_MODE0);
static const Carrier *gTuned = nullptr;

static inline void csLow()  { digitalWrite(PIN_CSN, LOW);  }
static inline void csHigh() { digitalWrite(PIN_CSN, HIGH); }

static void ccWrite(uint8_t addr, uint8_t value) {
  SPI.beginTransaction(kSpi);
  csLow();
  while (digitalRead(PIN_MISO)) {}
  SPI.transfer(addr);
  SPI.transfer(value);
  csHigh();
  SPI.endTransaction();
}

static uint8_t ccRead(uint8_t addr, bool status = false) {
  SPI.beginTransaction(kSpi);
  csLow();
  while (digitalRead(PIN_MISO)) {}
  SPI.transfer(addr | (status ? 0xC0 : 0x80));
  uint8_t v = SPI.transfer(0x00);
  csHigh();
  SPI.endTransaction();
  return v;
}

static void ccStrobe(uint8_t cmd) {
  SPI.beginTransaction(kSpi);
  csLow();
  while (digitalRead(PIN_MISO)) {}
  SPI.transfer(cmd);
  csHigh();
  SPI.endTransaction();
}

static void ccReset() {
  csHigh(); delayMicroseconds(5);
  csLow();  delayMicroseconds(10);
  csHigh(); delayMicroseconds(45);
  ccStrobe(CMD_SRES);
  delay(2);
}

// Everything except the carrier — that is switched per remote by ccTune().
static void ccConfigure() {
  ccWrite(REG_IOCFG2,   0x0D);   // GDO2 = asynchronous serial data output (RX)
  ccWrite(REG_IOCFG0,   0x2E);   // GDO0 high-Z; in async TX it is a data input
  ccWrite(REG_FIFOTHR,  0x47);
  ccWrite(REG_PKTCTRL0, 0x32);   // async serial, no CRC, infinite length
  ccWrite(REG_CHANNR,   0x00);
  ccWrite(REG_FSCTRL1,  0x06);
  ccWrite(REG_FSCTRL0,  0x00);
  // 58 kHz channel filter, ~4.8 kBaud. In async OOK the data rate only sets the
  // slicer/AGC time constants; a few times the ~1 kBaud symbol rate tracks the
  // shortest pulse (259 us on the fan) without ringing.
  ccWrite(REG_MDMCFG4,  0xF7);
  ccWrite(REG_MDMCFG3,  0x80);
  ccWrite(REG_MDMCFG2,  0x30);   // ASK/OOK, no Manchester, no sync word
  ccWrite(REG_MDMCFG1,  0x22);
  ccWrite(REG_MDMCFG0,  0xF8);
  ccWrite(REG_DEVIATN,  0x15);   // unused for OOK
  ccWrite(REG_MCSM1,    0x30);
  ccWrite(REG_MCSM0,    0x18);   // auto-calibrate on IDLE->RX/TX
  ccWrite(REG_FOCCFG,   0x16);
  ccWrite(REG_BSCFG,    0x6C);
  ccWrite(REG_AGCCTRL2, 0x03);   // OOK settings per TI DN022
  ccWrite(REG_AGCCTRL1, 0x00);
  ccWrite(REG_AGCCTRL0, 0x91);
  ccWrite(REG_FREND1,   0x56);
  ccWrite(REG_FREND0,   0x11);   // OOK: PA_POWER=1 -> PATABLE[0]=off, [1]=on
  ccWrite(REG_FSCAL3,   0xE9);
  ccWrite(REG_FSCAL2,   0x2A);
  ccWrite(REG_FSCAL1,   0x00);
  ccWrite(REG_FSCAL0,   0x1F);
  ccWrite(REG_TEST2,    0x81);
  ccWrite(REG_TEST1,    0x35);
  ccWrite(REG_TEST0,    0x09);

  SPI.beginTransaction(kSpi);
  csLow();
  while (digitalRead(PIN_MISO)) {}
  SPI.transfer(REG_PATABLE | 0x40);
  SPI.transfer(0x00);
  SPI.transfer(PA_POWER);
  csHigh();
  SPI.endTransaction();
}

// The two remotes are 164 kHz apart, well outside one channel filter, so the
// synthesiser is retuned and recalibrated whenever the target changes.
static void ccTune(const Carrier &c) {
  if (gTuned == &c) return;
  ccStrobe(CMD_SIDLE);
  ccWrite(REG_FREQ2, c.f2);
  ccWrite(REG_FREQ1, c.f1);
  ccWrite(REG_FREQ0, c.f0);
  ccStrobe(CMD_SCAL);
  delay(1);
  gTuned = &c;
}

// ----------------------------------------------------------- pulse-level TX

static void rxEnd();          // defined below; TX must not run with RX armed

static void txBegin() {
  rxEnd();
  pinMode(PIN_GDO0, OUTPUT);
  digitalWrite(PIN_GDO0, LOW);
  ccStrobe(CMD_STX);
  delay(2);                                  // let the PA and PLL settle
}

static void txEnd() {
  digitalWrite(PIN_GDO0, LOW);
  ccStrobe(CMD_SIDLE);
}

// Emit one mark/space pair against an absolute deadline. Scheduling against a
// running deadline rather than summing delays keeps a 100 ms frame from
// accumulating per-symbol drift.
static inline void txPulse(uint32_t &t, uint32_t highUs, uint32_t lowUs) {
  digitalWrite(PIN_GDO0, HIGH);
  t += highUs;
  while ((int32_t)(micros() - t) < 0) {}
  digitalWrite(PIN_GDO0, LOW);
  t += lowUs;
  while ((int32_t)(micros() - t) < 0) {}
}

// ------------------------------------------------ remote 01: ceiling fan (TX)

static Preferences gPrefs;
static uint8_t gFanCounter = 0;        // 3-bit, survives reboots

// bit28 = b20^b24, bit29 = !(b21^b25), bit30 = b22^b26, bit31 = !(b23^b27).
// Solved by GF(2) elimination over 45 captured frames, zero violations.
static void fanBuildFrame(uint8_t code, uint8_t counter, char *out) {
  memcpy(out, kFanAddress, 20);
  for (int i = 0; i < 5; i++) out[20 + i] = ((code >> (4 - i)) & 1) ? '1' : '0';
  for (int i = 0; i < 3; i++) out[25 + i] = ((counter >> (2 - i)) & 1) ? '1' : '0';
  const int b0 = out[20] - '0', b1 = out[21] - '0',
            b2 = out[22] - '0', b3 = out[23] - '0', b4 = out[24] - '0';
  const int c0 = out[25] - '0', c1 = out[26] - '0', c2 = out[27] - '0';
  out[28] = (b0 ^ b4) ? '1' : '0';
  out[29] = (1 ^ b1 ^ c0) ? '1' : '0';
  out[30] = (b2 ^ c1) ? '1' : '0';
  out[31] = (1 ^ b3 ^ c2) ? '1' : '0';
  out[32] = '0';
  out[33] = '\0';
}

// Press N of the fan remote. The counter is held constant across the repeats —
// that is what makes the receiver treat 8 frames as one press instead of eight,
// and it is why the fan does not jump 8 speed steps per button push.
static bool fanTransmit(uint8_t button1based) {
  if (button1based < 1 || button1based > FAN_BUTTON_COUNT) return false;
  char frame[FAN_FRAME_BITS + 1];
  fanBuildFrame(kFanButtonCode[button1based - 1], gFanCounter, frame);

  ccTune(kFanCarrier);
  txBegin();
  uint32_t t = micros();
  for (int r = 0; r < FAN_REPEATS; r++) {
    for (int i = 0; i < FAN_FRAME_BITS; i++) {
      const bool one = frame[i] == '1';
      const uint32_t hi = one ? FAN_LONG_HIGH_US : FAN_SHORT_HIGH_US;
      uint32_t lo = one ? FAN_SHORT_LOW_US : FAN_LONG_LOW_US;
      if (i == FAN_FRAME_BITS - 1 && r < FAN_REPEATS - 1) lo = FAN_FRAME_GAP_US;
      txPulse(t, hi, lo);
    }
  }
  txEnd();

  gFanCounter = (gFanCounter + 1) & 0x07;
  gPrefs.putUChar("fanctr", gFanCounter);
  return true;
}

// -------------------------------------------------- remote 02: blind (replay)

static inline bool frameBit(const uint8_t *bits, int i) {
  return (bits[i >> 3] >> (7 - (i & 7))) & 1;
}

static void blindFrame(const uint8_t *bits, uint32_t &t) {
  txPulse(t, HEADER_HIGH_US, HEADER_LOW_US);
  for (int i = 0; i < FRAME_BITS; i++) {
    const uint32_t mark = frameBit(bits, i) ? PULSE_LONG_US : PULSE_SHORT_US;
    txPulse(t, mark, SYMBOL_US - mark);
  }
}

static const CodeEntry *findCode(uint8_t channel, uint8_t action, uint8_t role) {
  for (size_t i = 0; i < kCodebookCount; i++) {
    const CodeEntry &e = kCodebook[i];
    if (e.channel == channel && e.action == action && e.role == role) return &e;
  }
  return nullptr;
}

// A tap sends the step code a few times. A hold reproduces what the real remote
// does — the step code exactly STEP_RUN times, then the full-travel code — which
// is what makes the receiver run to the end stop instead of nudging one step.
static bool blindTransmit(uint8_t channel, uint8_t action, bool hold) {
  const CodeEntry *step = findCode(channel, action, ROLE_STEP);
  if (!step) step = findCode(channel, action, ROLE_SINGLE);
  if (!step) return false;
  const CodeEntry *full = hold ? findCode(channel, action, ROLE_FULL) : nullptr;
  if (hold && !full) return false;

  const int stepReps = hold ? STEP_RUN : 6;
  const int fullReps = hold ? 12 : 0;

  ccTune(kBlindCarrier);
  txBegin();
  uint32_t next = micros();
  for (int i = 0; i < stepReps + fullReps; i++) {
    uint32_t t = next;
    blindFrame((i < stepReps) ? step->bits : full->bits, t);
    next += FRAME_PERIOD_US;
    while ((int32_t)(micros() - next) < 0) {}
  }
  txEnd();
  return true;
}

// ------------------------------------------------------- reception (checking)

// Not needed to drive anything — it is here so the bridge can prove what it
// transmitted, and so a codebook can be extended without the SDR.
static volatile uint32_t gEdgeUs[512];
static volatile uint16_t gEdgeCount = 0;

static void IRAM_ATTR onEdge() {
  // Read-modify-write on the volatile counter in one step: '++' on a volatile
  // is deprecated precisely because its load and store are separate, which is
  // not what you want in an interrupt handler.
  const uint16_t i = gEdgeCount;
  if (i < 512) {
    gEdgeUs[i] = micros();
    gEdgeCount = i + 1;
  }
}

static void rxBegin(const Carrier &c) {
  ccStrobe(CMD_SIDLE);
  ccTune(c);
  pinMode(PIN_GDO0, INPUT);
  pinMode(PIN_GDO2, INPUT);
  gEdgeCount = 0;
  attachInterrupt(digitalPinToInterrupt(PIN_GDO2), onEdge, CHANGE);
  ccStrobe(CMD_SRX);
}

static void rxEnd() {
  detachInterrupt(digitalPinToInterrupt(PIN_GDO2));
  ccStrobe(CMD_SIDLE);
}

// Slice the edge log with the given pulse widths. Returns bit count, 0 on miss.
static int rxDecode(char *out, size_t outLen, int wantBits,
                    uint32_t shortUs, uint32_t longUs, uint32_t hdrUs) {
  const uint16_t n = gEdgeCount;
  const uint32_t tol = (longUs - shortUs) / 3;       // half-way, with margin
  for (uint16_t s = 0; s + 1 < n; s++) {
    uint16_t i = s;
    if (hdrUs) {                                     // blind: skip the header
      const uint32_t high = gEdgeUs[s + 1] - gEdgeUs[s];
      if (high < hdrUs - 600 || high > hdrUs + 600) continue;
      i = s + 2;
    }
    int bits = 0;
    while (bits < wantBits && i + 1 < n) {
      const uint32_t mark = gEdgeUs[i + 1] - gEdgeUs[i];
      char b;
      if (mark > shortUs - tol && mark < shortUs + tol) b = '0';
      else if (mark > longUs - tol && mark < longUs + tol) b = '1';
      else break;
      if ((size_t)bits < outLen - 1) out[bits] = b;
      bits++;
      i += 2;
    }
    if (bits == wantBits) { out[bits] = '\0'; return bits; }
  }
  return 0;
}

// ------------------------------------------------------------- MQTT / HA glue

static WiFiClient gWifi;
static PubSubClient gMqtt(gWifi);
static char gBase[48];

static void publishDiscovery() {
  char topic[200], payload[800], uniq[64], cmdt[110];
  char devblk[160];
  snprintf(devblk, sizeof(devblk),
           "\"dev\":{\"ids\":[\"%s\"],\"name\":\"%s\",\"mf\":\"DIY\","
           "\"mdl\":\"ESP32+CC1101 447MHz\"}", DEVICE_ID, DEVICE_NAME);

  // --- blind: a cover per channel. Transmit-only, so no position feedback;
  //     HA is told that with optimistic mode rather than shown a fake state.
  for (size_t i = 0; i < kBlindChannelCount; i++) {
    const uint8_t ch = kBlindChannels[i];
    snprintf(uniq, sizeof(uniq), "%s_blind%02u", DEVICE_ID, ch);
    snprintf(cmdt, sizeof(cmdt), "%s/blind/%u/set", gBase, ch);
    snprintf(topic, sizeof(topic),
             "homeassistant/cover/%s/blind%02u/config", DEVICE_ID, ch);
    snprintf(payload, sizeof(payload),
             "{\"name\":\"Blind CH%02u\",\"uniq_id\":\"%s\",\"cmd_t\":\"%s\","
             "\"pl_open\":\"OPEN\",\"pl_cls\":\"CLOSE\",\"pl_stop\":\"STOP\","
             "\"opt\":true,\"dev_cla\":\"blind\",\"avty_t\":\"%s/status\",%s}",
             ch, uniq, cmdt, gBase, devblk);
    gMqtt.publish(topic, payload, true);

    const char *steps[] = {"up", "down"};
    for (int s = 0; s < 2; s++) {
      snprintf(topic, sizeof(topic),
               "homeassistant/button/%s/blind%02u_step_%s/config",
               DEVICE_ID, ch, steps[s]);
      snprintf(payload, sizeof(payload),
               "{\"name\":\"Blind CH%02u step %s\",\"uniq_id\":\"%s_st_%s\","
               "\"cmd_t\":\"%s/blind/%u/step_%s\",\"avty_t\":\"%s/status\",%s}",
               ch, steps[s], uniq, steps[s], gBase, ch, steps[s], gBase, devblk);
      gMqtt.publish(topic, payload, true);
    }
  }

  // --- fan: one button per remote key. What each key does on the fan has not
  //     been identified, so they are published by number and renamed in HA.
  for (int b = 1; b <= FAN_BUTTON_COUNT; b++) {
    snprintf(topic, sizeof(topic),
             "homeassistant/button/%s/fan%02d/config", DEVICE_ID, b);
    snprintf(payload, sizeof(payload),
             "{\"name\":\"Fan button %02d\",\"uniq_id\":\"%s_fan%02d\","
             "\"cmd_t\":\"%s/fan/%d/press\",\"avty_t\":\"%s/status\",%s}",
             b, DEVICE_ID, b, gBase, b, gBase, devblk);
    gMqtt.publish(topic, payload, true);
  }

  Serial.printf("[HA] 블라인드 %u채널 + 팬 버튼 %d개 발행\n",
                (unsigned)kBlindChannelCount, FAN_BUTTON_COUNT);
}

static void afterTx() { rxBegin(kBlindCarrier); }

static void doBlind(uint8_t ch, uint8_t action, bool hold) {
  Serial.printf("[TX] blind ch%02u %s %s ... ", ch, kActionNames[action],
                hold ? "(완전이동)" : "(스텝)");
  Serial.println(blindTransmit(ch, action, hold) ? "완료" : "실패 — 코드북에 없음");
  afterTx();
}

static void doFan(int button) {
  Serial.printf("[TX] fan 버튼 %02d (카운터 %u) ... ", button, gFanCounter);
  Serial.println(fanTransmit(button) ? "완료" : "실패 — 버튼 번호 범위 밖");
  afterTx();
}

static void onMqtt(char *topic, byte *payload, unsigned int len) {
  char msg[16] = {0};
  for (unsigned i = 0; i < len && i < sizeof(msg) - 1; i++) msg[i] = payload[i];

  unsigned ch = 0;
  int btn = 0;
  char dir[8] = {0};

  if (sscanf(topic, "%*[^/]/blind/%u/set", &ch) == 1) {
    if (!strcmp(msg, "OPEN"))       doBlind(ch, ACT_UP, true);
    else if (!strcmp(msg, "CLOSE")) doBlind(ch, ACT_DOWN, true);
    else if (!strcmp(msg, "STOP"))  doBlind(ch, ACT_ENTER, false);
    return;
  }
  if (sscanf(topic, "%*[^/]/blind/%u/step_%7s", &ch, dir) == 2) {
    doBlind(ch, strcmp(dir, "up") == 0 ? ACT_UP : ACT_DOWN, false);
    return;
  }
  if (sscanf(topic, "%*[^/]/fan/%d/press", &btn) == 1) doFan(btn);
}

static void mqttConnect() {
  static uint32_t lastTry = 0;
  if (millis() - lastTry < 3000) return;
  lastTry = millis();

  char willTopic[80];
  snprintf(willTopic, sizeof(willTopic), "%s/status", gBase);
  const bool ok = (MQTT_USER[0] == '\0')
      ? gMqtt.connect(DEVICE_ID, willTopic, 0, true, "offline")
      : gMqtt.connect(DEVICE_ID, MQTT_USER, MQTT_PASS,
                      willTopic, 0, true, "offline");
  if (!ok) { Serial.printf("[MQTT] 재시도 (rc=%d)\n", gMqtt.state()); return; }

  gMqtt.publish(willTopic, "online", true);
  char sub[80];
  snprintf(sub, sizeof(sub), "%s/blind/+/+", gBase); gMqtt.subscribe(sub);
  snprintf(sub, sizeof(sub), "%s/fan/+/press", gBase); gMqtt.subscribe(sub);
  publishDiscovery();
  Serial.println("[MQTT] 연결됨");
}

// ------------------------------------------------------------ serial console

// Bench testing before WiFi exists.
//   fan 3            press fan button 3
//   blind 1 down hold
//   rx fan | rx blind
//   regs
static void handleSerial() {
  if (!Serial.available()) return;
  String line = Serial.readStringUntil('\n');
  line.trim();
  if (!line.length()) return;

  if (line == "regs") {
    Serial.printf("PARTNUM=0x%02X VERSION=0x%02X MARCSTATE=0x%02X RSSI=%ddBm "
                  "tuned=%s fanctr=%u\n",
                  ccRead(REG_PARTNUM, true), ccRead(REG_VERSION, true),
                  ccRead(REG_MARCSTATE, true) & 0x1F,
                  (int8_t)ccRead(REG_RSSI, true) / 2 - 74,
                  gTuned ? gTuned->name : "none", gFanCounter);
    return;
  }
  if (line.startsWith("rx")) {
    const bool fan = line.indexOf("fan") > 0;
    Serial.printf("[RX] %s 5초 수신...\n", fan ? "팬" : "블라인드");
    rxBegin(fan ? kFanCarrier : kBlindCarrier);
    const uint32_t until = millis() + 5000;
    while (millis() < until) delay(10);
    char bits[128];
    const int n = fan
        ? rxDecode(bits, sizeof(bits), FAN_FRAME_BITS,
                   FAN_SHORT_HIGH_US, FAN_LONG_HIGH_US, 0)
        : rxDecode(bits, sizeof(bits), FRAME_BITS,
                   PULSE_SHORT_US, PULSE_LONG_US, HEADER_HIGH_US);
    Serial.printf("[RX] 엣지 %u개 → %s\n", gEdgeCount, n ? bits : "프레임 없음");
    return;
  }
  int a = 0; char act[12] = {0}, mode[12] = {0};
  if (sscanf(line.c_str(), "fan %d", &a) == 1) { doFan(a); return; }
  const int got = sscanf(line.c_str(), "blind %d %11s %11s", &a, act, mode);
  if (got >= 2) {
    for (int i = 0; i < ACT_COUNT; i++) {
      if (!strcmp(act, kActionNames[i])) {
        doBlind(a, i, got >= 3 && !strcmp(mode, "hold"));
        return;
      }
    }
  }
  Serial.println("사용법: fan <1-15> | blind <ch> <up|down|enter|custom> [hold] "
                 "| rx [fan|blind] | regs");
}

// --------------------------------------------------------------------- setup

void setup() {
  Serial.begin(115200);
  delay(300);
  Serial.println("\n447MHz RF bridge — fan(01) + blind(02)");

  pinMode(PIN_CSN, OUTPUT);
  csHigh();
  pinMode(PIN_GDO0, OUTPUT);
  digitalWrite(PIN_GDO0, LOW);
  pinMode(PIN_GDO2, INPUT);
  SPI.begin(PIN_SCK, PIN_MISO, PIN_MOSI, PIN_CSN);

  ccReset();
  const uint8_t ver = ccRead(REG_VERSION, true);
  Serial.printf("CC1101 PARTNUM=0x%02X VERSION=0x%02X %s\n",
                ccRead(REG_PARTNUM, true), ver,
                (ver == 0x14 || ver == 0x04) ? "OK" : "<-- 배선/전원 확인");
  ccConfigure();

  // The fan's counter must continue across reboots: the receiver rejects a
  // value it has already consumed as a repeat of the previous press.
  gPrefs.begin("rf447", false);
  gFanCounter = gPrefs.getUChar("fanctr", 0) & 0x07;
  Serial.printf("블라인드 코드 %u개 / 채널 %u개, 팬 버튼 %d개 (카운터 %u)\n",
                (unsigned)kCodebookCount, (unsigned)kBlindChannelCount,
                FAN_BUTTON_COUNT, gFanCounter);

  snprintf(gBase, sizeof(gBase), "%s", DEVICE_ID);

  // Say plainly that nothing was configured, rather than letting a 10-second
  // connect attempt look like a network fault.
  if (WIFI_SSID[0] == '\0') {
    Serial.println("[!] WiFi/MQTT 미설정 — 시리얼 명령만 동작합니다.");
    Serial.println("    rf_bridge.ino 상단 6줄을 채우고 다시 플래시하세요 (FLASH.md).");
    rxBegin(kBlindCarrier);
    return;
  }

  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  Serial.print("WiFi");
  for (int i = 0; i < 40 && WiFi.status() != WL_CONNECTED; i++) {
    delay(250); Serial.print(".");
  }
  if (WiFi.status() == WL_CONNECTED) {
    Serial.printf(" %s\n", WiFi.localIP().toString().c_str());
    gMqtt.setServer(MQTT_HOST, MQTT_PORT);
    gMqtt.setCallback(onMqtt);
    gMqtt.setBufferSize(1024);          // discovery payloads exceed the default
  } else {
    Serial.println(" 실패 — 시리얼 명령만 사용 가능");
  }
  rxBegin(kBlindCarrier);
}

void loop() {
  if (WiFi.status() == WL_CONNECTED) {
    if (!gMqtt.connected()) mqttConnect();
    else gMqtt.loop();
  }
  handleSerial();
}
